### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by YaoHuanyu** [puaqieshang/automatic-labeling-heart-vessels#1]
Thank you very much for sharing. Can you provide some training data or the format of its labeling as a reference? Thanks again.

**Comment by ivan-pua** [comment]
[AutoMeshing_centerline.txt](https://github.com/puaqieshang/automatic-labeling-heart-vessels/files/5848683/AutoMeshing_centerline.txt)

Hi Yao, the raw data looks like this, where the columns represent the coronary artery branch number, x, y, z coordinates and radius of the centrelines points.

**Comment by YaoHuanyu** [comment]
Got it. Thank you very much!
