### ISSUE TITLE
About cadtoolkit.pc2g library

### ISSUE THREAD

**Issue by bhaswara** [puaqieshang/automatic-labeling-heart-vessels#2]
Hi @ivan-pua, this is a nice paper and work. I'm interested on understanding the code. There is a library that you use **cadtoolkit.pc2g**. I was looking into your code but cannot find it. I wonder if you can share this. Thank you.

**Comment by ivan-pua** [comment]
Thanks for reaching out @bhaswara. This library is a private module that my research team have written 4 years ago. This code belongs to them hence it's "private". I'm no longer in that research team anymore so unfortunately I can't give you the code. Hope you could understand.
